listen_addresses = '127.0.0.1'
port = 5432
max_connections = 100
shared_buffers = 128MB
logging_collector = off
log_destination = 'stderr'
ssl = off
hba_file = 'D:/Projects/Locora/usr/config/postgresql/pg_hba.conf'
external_pid_file = 'D:/Projects/Locora/temp/postgresql/postgresql.pid'