[client]
port=3306
default-character-set=utf8mb4

[mysqld]
port=3306
basedir="D:\Projects\Locora\bin\mariadb\current"
datadir="D:\Projects\Locora\data\mariadb"
tmpdir="D:\Projects\Locora\temp\mariadb"
bind-address=127.0.0.1
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci
skip-name-resolve
log-error="D:\Projects\Locora\usr\logs\mariadb.stderr.log"
general_log_file="D:\Projects\Locora\usr\logs\mariadb.stdout.log"
general_log=0
max_connections=100
sql_mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION