server {
    listen       80;
    server_name  welcome.locora.test;
    root         "D:/Projects/Locora/www/welcome";
    index        index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        return 501;
    }
}