namespace Locora.Domain.Entities;

public sealed record EnvironmentSnapshot(
    string EnvironmentRoot,
    string ActiveProfile,
    IReadOnlyList<ServiceDescriptor> Services,
    IReadOnlyList<ServicePresetStatus> ServicePresets,
    IReadOnlyList<ProjectDescriptor> Projects,
    IReadOnlyList<HealthIssue> Issues,
    IReadOnlyList<ValidationResult> ValidationResults,
    IReadOnlyList<PortDiagnostic> PortDiagnostics,
    IReadOnlyList<PermissionDiagnostic> PermissionDiagnostics,
    IReadOnlyList<PackageSourceStatus> PackageSources,
    PackageRegistrySummary PackageRegistry,
    IReadOnlyList<PackageDownloadStatus> PackageDownloads,
    PackageDownloadSummary PackageDownloadsSummary,
    IReadOnlyList<RuntimePackageStatus> RuntimePackages,
    RuntimePackageSummary RuntimePackageSummary,
    IReadOnlyList<ToolPackageStatus> ToolPackages,
    ToolPackageSummary ToolPackageSummary,
    IReadOnlyList<StackProfileStatus> StackProfiles,
    StackProfileSummary StackProfileSummary,
    SslStatus SslStatus,
    DateTimeOffset GeneratedAt,
    bool IsSupervisorReachable,
    bool IsSupervisorElevated,
    int? SupervisorProcessId);
