worker_processes  1;

error_log  "D:/Projects/Locora/usr/logs/nginx.stderr.log";
pid        "D:/Projects/Locora/temp/nginx/nginx.pid";

events {
    worker_connections  1024;
}

http {
    
    default_type  application/octet-stream;

    access_log    "D:/Projects/Locora/usr/logs/nginx.stdout.log";
    sendfile      on;
    keepalive_timeout  65;
    client_body_temp_path "D:/Projects/Locora/temp/nginx/client_temp";
    proxy_temp_path       "D:/Projects/Locora/temp/nginx/proxy_temp";
    fastcgi_temp_path     "D:/Projects/Locora/temp/nginx/fastcgi_temp";
    uwsgi_temp_path       "D:/Projects/Locora/temp/nginx/uwsgi_temp";
    scgi_temp_path        "D:/Projects/Locora/temp/nginx/scgi_temp";

    server {
        listen       80;
        server_name  localhost *.locora.test;
        root         "D:/Projects/Locora/www";
        index        index.php index.html index.htm;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            return 501;
        }
    }

    include "D:/Projects/Locora/usr/config/nginx/vhosts/*.conf";
}