[CmdletBinding()]
param(
    [string]$Version = '',
    [string]$Configuration = 'Release',
    [string]$RuntimeIdentifier = 'win-x64',
    [switch]$IncludeRuntimeBinaries,
    [switch]$IncludePackageCache,
    [switch]$IncludeUserData,
    [switch]$SkipPublish,
    [string]$Channel = 'stable',
    [string]$ReleasePageUri = ''
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
if ([string]::IsNullOrWhiteSpace($Version)) {
    if ($env:GITHUB_REF_TYPE -eq 'tag' -and -not [string]::IsNullOrWhiteSpace($env:GITHUB_REF_NAME)) {
        $Version = $env:GITHUB_REF_NAME.TrimStart('v')
    }
    elseif (-not [string]::IsNullOrWhiteSpace($env:GITHUB_RUN_NUMBER)) {
        $Version = "0.0.0-ci.$($env:GITHUB_RUN_NUMBER)"
    }
    else {
        $Version = '0.0.0-local'
    }
}

$safeVersion = ($Version -replace '[^\w\.-]', '-').Trim('-')
if ([string]::IsNullOrWhiteSpace($safeVersion)) {
    throw 'Version resolved to an empty package label.'
}

$publishRoot = Join-Path $root "artifacts\publish\Locora.App-$RuntimeIdentifier"
$distRoot = Join-Path $root 'artifacts\dist'
$stageRoot = Join-Path $distRoot "Locora-$safeVersion-$RuntimeIdentifier"
$zipPath = Join-Path $distRoot "Locora-$safeVersion-$RuntimeIdentifier-portable.zip"
$checksumsPath = Join-Path $distRoot 'checksums.txt'
$releaseManifestPath = Join-Path $distRoot 'release-manifest.json'

function Copy-DirectoryContents {
    param(
        [Parameter(Mandatory = $true)]
        [string]$SourcePath,
        [Parameter(Mandatory = $true)]
        [string]$DestinationPath
    )

    if (-not (Test-Path -LiteralPath $SourcePath)) {
        return
    }

    New-Item -ItemType Directory -Force -Path $DestinationPath | Out-Null
    Get-ChildItem -LiteralPath $SourcePath -Force | Copy-Item -Destination $DestinationPath -Recurse -Force
}

New-Item -ItemType Directory -Force -Path $publishRoot, $distRoot | Out-Null

if (-not $SkipPublish) {
    $projectPath = Join-Path $root 'src\Locora.App\Locora.App.csproj'
    & dotnet publish $projectPath -c $Configuration -r $RuntimeIdentifier --self-contained false -p:WindowsPackageType=None -p:AllowUnsafeBlocks=true -o $publishRoot
    if ($LASTEXITCODE -ne 0) {
        throw "dotnet publish failed with exit code $LASTEXITCODE."
    }
}

if (-not (Test-Path -LiteralPath $publishRoot)) {
    throw "Publish folder does not exist: $publishRoot"
}

if (Test-Path -LiteralPath $stageRoot) {
    Remove-Item -LiteralPath $stageRoot -Recurse -Force
}
New-Item -ItemType Directory -Force -Path $stageRoot | Out-Null

Copy-DirectoryContents $publishRoot $stageRoot

$portableDirs = @(
    'usr',
    'usr\config',
    'usr\logs',
    'usr\profiles',
    'usr\aliases',
    'usr\shell',
    'usr\templates',
    'usr\cache',
    'usr\updates',
    'usr\distribution',
    'www',
    'bin',
    'data',
    'temp',
    'archives',
    'package-manifests'
)

foreach ($relativePath in $portableDirs) {
    New-Item -ItemType Directory -Force -Path (Join-Path $stageRoot $relativePath) | Out-Null
}

$packageManifestsRoot = Join-Path $root 'package-manifests'
Copy-DirectoryContents $packageManifestsRoot (Join-Path $stageRoot 'package-manifests')

if ($IncludeUserData) {
    foreach ($relativePath in @('usr\config', 'usr\profiles', 'www', 'data')) {
        $sourcePath = Join-Path $root $relativePath
        Copy-DirectoryContents $sourcePath (Join-Path $stageRoot $relativePath)
    }
}

if ($IncludeRuntimeBinaries) {
    $binRoot = Join-Path $root 'bin'
    Copy-DirectoryContents $binRoot (Join-Path $stageRoot 'bin')
}

if ($IncludePackageCache) {
    $packageCacheRoot = Join-Path $root 'usr\cache\packages'
    Copy-DirectoryContents $packageCacheRoot (Join-Path $stageRoot 'usr\cache\packages')
}

Set-Content -Encoding UTF8 -Path (Join-Path $stageRoot 'README.txt') -Value @"
Locora portable distribution

Extract this folder anywhere writable, then run Locora.App.exe.
The first run creates or refreshes usr/config, usr/logs, package manifests, and portable workspace folders.
"@

if (Test-Path -LiteralPath $zipPath) {
    Remove-Item -LiteralPath $zipPath -Force
}
Compress-Archive -LiteralPath $stageRoot -DestinationPath $zipPath -CompressionLevel Optimal

$hash = (Get-FileHash -Algorithm SHA256 -LiteralPath $zipPath).Hash.ToLowerInvariant()
Set-Content -Encoding UTF8 -Path $checksumsPath -Value "$hash  $(Split-Path $zipPath -Leaf)"

$releaseManifest = [ordered]@{
    schema = 'locora.app-update.v1'
    appId = 'locora'
    channel = $Channel
    version = $Version
    releaseDate = (Get-Date).ToString('yyyy-MM-dd')
    releaseNotes = 'Portable distribution generated by packaging automation.'
    releasePageUri = $ReleasePageUri
    downloadUri = (Split-Path $zipPath -Leaf)
    sha256 = $hash
    minimumSupportedVersion = '0.1.0'
    requiresManualInstall = $true
    assets = @(
        [ordered]@{
            platform = 'windows'
            architecture = 'x64'
            downloadUri = (Split-Path $zipPath -Leaf)
            sha256 = $hash
        }
    )
}
$releaseManifest | ConvertTo-Json -Depth 6 | Set-Content -Encoding UTF8 -Path $releaseManifestPath

Write-Host "Portable distribution created: $zipPath"
Write-Host "SHA-256: $hash"
Write-Host "Release manifest: $releaseManifestPath"
