using System.Reflection;
using System.Text;
using System.Text.Json;
using Locora.Application.Abstractions;
using Locora.Infrastructure.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace Locora.App.Services;

public sealed class PortableDistributionService : IPortableDistributionService
{
    private static readonly JsonSerializerOptions SerializerOptions = new()
    {
        WriteIndented = true
    };

    private readonly IEnvironmentPaths _environmentPaths;
    private readonly PortableDistributionSettings _settings;
    private readonly AppUpdateSettings _updateSettings;
    private readonly ILogger<PortableDistributionService> _logger;

    public PortableDistributionService(
        IEnvironmentPaths environmentPaths,
        IOptions<AppSettings> settings,
        ILogger<PortableDistributionService> logger)
    {
        _environmentPaths = environmentPaths;
        _settings = settings.Value.Distribution;
        _updateSettings = settings.Value.Updates;
        _logger = logger;
    }

    public PortableDistributionFiles RefreshDistributionFiles()
    {
        Directory.CreateDirectory(_environmentPaths.PortableDistributionRoot);
        Directory.CreateDirectory(_environmentPaths.PortableDistributionArtifactsRoot);

        File.WriteAllText(_environmentPaths.PortableDistributionScriptFile, BuildDistributionScript(), Encoding.UTF8);
        File.WriteAllText(_environmentPaths.PortableDistributionPlanFile, BuildPlan(), Encoding.UTF8);
        File.WriteAllText(_environmentPaths.PortableDistributionReadmeFile, BuildReadme(), Encoding.UTF8);
        File.WriteAllText(_environmentPaths.PortableDistributionManifestTemplateFile, BuildReleaseManifestTemplate(), Encoding.UTF8);

        _logger.LogInformation(
            "Portable distribution files refreshed at {Root}.",
            _environmentPaths.PortableDistributionRoot);

        return new PortableDistributionFiles(
            _environmentPaths.PortableDistributionRoot,
            _environmentPaths.PortableDistributionArtifactsRoot,
            _environmentPaths.PortableDistributionScriptFile,
            _environmentPaths.PortableDistributionPlanFile,
            _environmentPaths.PortableDistributionReadmeFile,
            _environmentPaths.PortableDistributionManifestTemplateFile,
            ResolveConfiguration(),
            ResolveRuntimeIdentifier(),
            _settings.IncludeRuntimeBinaries,
            _settings.IncludePackageCache,
            _settings.IncludeUserData,
            _settings.CreateReleaseManifest);
    }

    private string BuildPlan()
    {
        var plan = new
        {
            GeneratedAt = DateTimeOffset.Now,
            Mode = "portable-zip",
            Configuration = ResolveConfiguration(),
            RuntimeIdentifier = ResolveRuntimeIdentifier(),
            IncludeRuntimeBinaries = _settings.IncludeRuntimeBinaries,
            IncludePackageCache = _settings.IncludePackageCache,
            IncludeUserData = _settings.IncludeUserData,
            CreateReleaseManifest = _settings.CreateReleaseManifest,
            Script = _environmentPaths.PortableDistributionScriptFile,
            ArtifactsRoot = _environmentPaths.PortableDistributionArtifactsRoot,
            ReleaseManifestTemplate = _environmentPaths.PortableDistributionManifestTemplateFile,
            OutputConventions = new
            {
                StageFolder = "artifacts/dist/Locora-<version>-<rid>",
                ZipFile = "artifacts/dist/Locora-<version>-<rid>-portable.zip",
                Checksums = "artifacts/dist/checksums.txt",
                ReleaseManifest = "artifacts/dist/release-manifest.json"
            },
            ManualSteps = new[]
            {
                "Run the generated PowerShell script from the repository root after the WinUI app build is healthy.",
                "Review checksums.txt and release-manifest.json before publishing artifacts.",
                "Publish the zip and point Locora:Updates:ManifestUri at the release manifest."
            }
        };

        return JsonSerializer.Serialize(plan, SerializerOptions);
    }

    private string BuildDistributionScript()
    {
        return $$"""
# Generated by Locora. Review before running.
# Creates a portable ZIP distribution and a release manifest compatible with Locora app update checks.
[CmdletBinding()]
param(
    [string]$Version = '',
    [string]$Configuration = '{{EscapePowerShellSingleQuotedString(ResolveConfiguration())}}',
    [string]$RuntimeIdentifier = '{{EscapePowerShellSingleQuotedString(ResolveRuntimeIdentifier())}}',
    [switch]$IncludeRuntimeBinaries,
    [switch]$IncludePackageCache,
    [switch]$IncludeUserData,
    [switch]$SkipPublish
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$root = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
if ([string]::IsNullOrWhiteSpace($Version)) {
    $Version = '{{EscapePowerShellSingleQuotedString(ResolveCurrentVersion())}}'
}

$safeVersion = ($Version -replace '[^\w\.-]', '-').Trim('-')
if ([string]::IsNullOrWhiteSpace($safeVersion)) {
    throw 'Version resolved to an empty package label.'
}

$publishRoot = Join-Path $root "artifacts\publish\Locora.App-$RuntimeIdentifier"
$distRoot = Join-Path $root 'artifacts\dist'
$stageRoot = Join-Path $distRoot "Locora-$safeVersion-$RuntimeIdentifier"
$zipPath = Join-Path $distRoot "Locora-$safeVersion-$RuntimeIdentifier-portable.zip"
$checksumsPath = Join-Path $distRoot 'checksums.txt'
$releaseManifestPath = Join-Path $distRoot 'release-manifest.json'

function Copy-DirectoryContents {
    param(
        [Parameter(Mandatory = $true)]
        [string]$SourcePath,
        [Parameter(Mandatory = $true)]
        [string]$DestinationPath
    )

    if (-not (Test-Path -LiteralPath $SourcePath)) {
        return
    }

    New-Item -ItemType Directory -Force -Path $DestinationPath | Out-Null
    Get-ChildItem -LiteralPath $SourcePath -Force | Copy-Item -Destination $DestinationPath -Recurse -Force
}

New-Item -ItemType Directory -Force -Path $publishRoot, $distRoot | Out-Null

if (-not $SkipPublish) {
    $projectPath = Join-Path $root 'src\Locora.App\Locora.App.csproj'
    & dotnet publish $projectPath -c $Configuration -r $RuntimeIdentifier --self-contained true -p:SelfContained=true -p:WindowsPackageType=None -p:WindowsAppSDKSelfContained=true -p:AllowUnsafeBlocks=true -p:PublishSingleFile=false -o $publishRoot
    if ($LASTEXITCODE -ne 0) {
        throw "dotnet publish failed with exit code $LASTEXITCODE."
    }
}

if (-not (Test-Path -LiteralPath $publishRoot)) {
    throw "Publish folder does not exist: $publishRoot"
}

if (Test-Path -LiteralPath $stageRoot) {
    Remove-Item -LiteralPath $stageRoot -Recurse -Force
}
New-Item -ItemType Directory -Force -Path $stageRoot | Out-Null

Copy-DirectoryContents $publishRoot $stageRoot

$portableDirs = @(
    'usr',
    'usr\config',
    'usr\logs',
    'usr\profiles',
    'usr\aliases',
    'usr\shell',
    'usr\templates',
    'usr\cache',
    'usr\updates',
    'usr\distribution',
    'www',
    'bin',
    'data',
    'temp',
    'archives',
    'package-manifests'
)
foreach ($relativePath in $portableDirs) {
    New-Item -ItemType Directory -Force -Path (Join-Path $stageRoot $relativePath) | Out-Null
}

$packageManifestsRoot = Join-Path $root 'package-manifests'
Copy-DirectoryContents $packageManifestsRoot (Join-Path $stageRoot 'package-manifests')

if ($IncludeUserData) {
    foreach ($relativePath in @('usr\config', 'usr\profiles', 'www', 'data')) {
        $sourcePath = Join-Path $root $relativePath
        Copy-DirectoryContents $sourcePath (Join-Path $stageRoot $relativePath)
    }
}

if ($IncludeRuntimeBinaries) {
    $binRoot = Join-Path $root 'bin'
    Copy-DirectoryContents $binRoot (Join-Path $stageRoot 'bin')
}

if ($IncludePackageCache) {
    $packageCacheRoot = Join-Path $root 'usr\cache\packages'
    Copy-DirectoryContents $packageCacheRoot (Join-Path $stageRoot 'usr\cache\packages')
}

Set-Content -Encoding UTF8 -Path (Join-Path $stageRoot 'README.txt') -Value @"
Locora portable distribution

Extract this folder anywhere writable, then run Locora.App.exe.
This build is self-contained for .NET and Windows App SDK dependencies.
The first run creates or refreshes usr/config, usr/logs, package manifests, and portable workspace folders.
"@

if (Test-Path -LiteralPath $zipPath) {
    Remove-Item -LiteralPath $zipPath -Force
}
Compress-Archive -LiteralPath $stageRoot -DestinationPath $zipPath -CompressionLevel Optimal

$hash = (Get-FileHash -Algorithm SHA256 -LiteralPath $zipPath).Hash.ToLowerInvariant()
Set-Content -Encoding UTF8 -Path $checksumsPath -Value "$hash  $(Split-Path $zipPath -Leaf)"

$releaseManifest = [ordered]@{
    schema = 'locora.app-update.v1'
    appId = 'locora'
    channel = '{{EscapePowerShellSingleQuotedString(ResolveUpdateChannel())}}'
    version = $Version
    releaseDate = (Get-Date).ToString('yyyy-MM-dd')
    releaseNotes = 'Self-contained portable distribution generated by Locora packaging automation.'
    releasePageUri = '{{EscapePowerShellSingleQuotedString(_updateSettings.ReleasePageUri)}}'
    downloadUri = (Split-Path $zipPath -Leaf)
    sha256 = $hash
    minimumSupportedVersion = '0.1.0'
    requiresManualInstall = $true
    assets = @(
        [ordered]@{
            platform = 'windows'
            architecture = 'x64'
            downloadUri = (Split-Path $zipPath -Leaf)
            sha256 = $hash
        }
    )
}
$releaseManifest | ConvertTo-Json -Depth 6 | Set-Content -Encoding UTF8 -Path $releaseManifestPath

Write-Host "Portable distribution created: $zipPath"
Write-Host "SHA-256: $hash"
Write-Host "Release manifest: $releaseManifestPath"
""";
    }

    private string BuildReadme()
    {
        return $"""
# Locora Portable Distribution

This folder contains generated release packaging helpers for a portable Locora ZIP build.

## Files

- `build-portable-distribution.ps1` publishes `Locora.App`, stages the portable folder layout, creates a ZIP, writes `checksums.txt`, and emits a release manifest compatible with the app update checker.
- `portable-distribution-plan.json` records the configured packaging defaults.
- `release-manifest.template.json` shows the update-manifest schema to publish next to a release.

## Default Command

```powershell
powershell -ExecutionPolicy Bypass -File "{_environmentPaths.PortableDistributionScriptFile}"
```

The script stops if `dotnet publish` fails. Fix the app build first, then rerun the script.
""";
    }

    private string BuildReleaseManifestTemplate()
    {
        var template = new
        {
            schema = "locora.app-update.v1",
            appId = "locora",
            channel = ResolveUpdateChannel(),
            version = ResolveCurrentVersion(),
            releaseDate = DateTimeOffset.Now.ToString("yyyy-MM-dd"),
            releaseNotes = "Describe notable fixes, migration notes, and manual install steps.",
            releasePageUri = string.IsNullOrWhiteSpace(_updateSettings.ReleasePageUri) ? "https://example.com/locora/releases" : _updateSettings.ReleasePageUri,
            downloadUri = "Locora-<version>-win-x64-portable.zip",
            sha256 = "replace-with-lowercase-sha256",
            minimumSupportedVersion = "0.1.0",
            requiresManualInstall = true,
            assets = new[]
            {
                new
                {
                    platform = "windows",
                    architecture = "x64",
                    downloadUri = "Locora-<version>-win-x64-portable.zip",
                    sha256 = "replace-with-lowercase-sha256"
                }
            }
        };

        return JsonSerializer.Serialize(template, SerializerOptions);
    }

    private string ResolveConfiguration()
    {
        return string.IsNullOrWhiteSpace(_settings.Configuration) ? "Release" : _settings.Configuration.Trim();
    }

    private string ResolveRuntimeIdentifier()
    {
        return string.IsNullOrWhiteSpace(_settings.RuntimeIdentifier) ? "win-x64" : _settings.RuntimeIdentifier.Trim();
    }

    private string ResolveUpdateChannel()
    {
        return string.IsNullOrWhiteSpace(_updateSettings.Channel) ? "stable" : _updateSettings.Channel.Trim();
    }

    private static string ResolveCurrentVersion()
    {
        var assembly = typeof(PortableDistributionService).Assembly;
        var informationalVersion = assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion;
        return string.IsNullOrWhiteSpace(informationalVersion)
            ? assembly.GetName().Version?.ToString() ?? "0.0.0"
            : informationalVersion;
    }

    private static string EscapePowerShellSingleQuotedString(string value)
    {
        return value.Replace("'", "''", StringComparison.Ordinal);
    }
}
