using System.Text;
using System.Text.Json;
using Locora.Application.Abstractions;
using Microsoft.Extensions.Logging;

namespace Locora.App.Services;

public sealed class UserEnvironmentChangeService : IUserEnvironmentChangeService
{
    private static readonly JsonSerializerOptions ManifestSerializerOptions = new()
    {
        WriteIndented = true
    };

    private readonly IEnvironmentPaths _environmentPaths;
    private readonly ILogger<UserEnvironmentChangeService> _logger;

    public UserEnvironmentChangeService(
        IEnvironmentPaths environmentPaths,
        ILogger<UserEnvironmentChangeService> logger)
    {
        _environmentPaths = environmentPaths;
        _logger = logger;
    }

    public UserEnvironmentChangeFiles RefreshChangeFiles()
    {
        Directory.CreateDirectory(_environmentPaths.ShellIntegrationRoot);
        Directory.CreateDirectory(_environmentPaths.AliasesRoot);
        Directory.CreateDirectory(_environmentPaths.UserEnvironmentBackupRoot);

        var pathEntries = new[] { _environmentPaths.AliasesRoot };
        var variables = CreateManagedVariables();

        File.WriteAllText(
            _environmentPaths.UserEnvironmentApplyScriptFile,
            BuildApplyScript(pathEntries, variables),
            Encoding.UTF8);
        File.WriteAllText(
            _environmentPaths.UserEnvironmentRemoveScriptFile,
            BuildRemoveScript(pathEntries, variables.Keys),
            Encoding.UTF8);
        File.WriteAllText(
            _environmentPaths.UserEnvironmentManifestFile,
            BuildManifest(pathEntries, variables),
            Encoding.UTF8);

        _logger.LogInformation(
            "User environment change files refreshed at {Root}.",
            _environmentPaths.ShellIntegrationRoot);

        return new UserEnvironmentChangeFiles(
            _environmentPaths.ShellIntegrationRoot,
            _environmentPaths.UserEnvironmentApplyScriptFile,
            _environmentPaths.UserEnvironmentRemoveScriptFile,
            _environmentPaths.UserEnvironmentManifestFile,
            _environmentPaths.UserEnvironmentBackupRoot,
            pathEntries,
            variables);
    }

    private IReadOnlyDictionary<string, string> CreateManagedVariables()
    {
        return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["LOCORA_ROOT"] = _environmentPaths.AppRoot,
            ["LOCORA_ALIASES_ROOT"] = _environmentPaths.AliasesRoot,
            ["LOCORA_BIN"] = _environmentPaths.BinRoot,
            ["LOCORA_CONFIG"] = _environmentPaths.ConfigRoot,
            ["LOCORA_DATA"] = _environmentPaths.DataRoot,
            ["LOCORA_LOGS"] = _environmentPaths.LogsRoot,
            ["LOCORA_TEMP"] = _environmentPaths.TempRoot,
            ["LOCORA_PACKAGE_CACHE"] = _environmentPaths.PackageCacheRoot
        };
    }

    private string BuildApplyScript(
        IReadOnlyCollection<string> pathEntries,
        IReadOnlyDictionary<string, string> variables)
    {
        return $$"""
# Generated by Locora. Review before running.
# Scope: current Windows user only. No administrator rights are required.
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$managedPathEntries = @(
{{FormatPowerShellStringArray(pathEntries)}}
)

$managedVariables = [ordered]@{
{{FormatPowerShellHashtable(variables)}}
}

$backupRoot = '{{EscapePowerShellSingleQuotedString(_environmentPaths.UserEnvironmentBackupRoot)}}'
New-Item -ItemType Directory -Force -Path $backupRoot | Out-Null
$backupPath = Join-Path $backupRoot ('user-environment-before-locora-{0}.json' -f (Get-Date -Format 'yyyyMMdd-HHmmss'))
$backup = [ordered]@{
    CreatedAt = (Get-Date).ToString('o')
    Scope = 'CurrentUser'
    Path = [Environment]::GetEnvironmentVariable('Path', 'User')
    Variables = [ordered]@{}
}
foreach ($name in $managedVariables.Keys) {
    $backup.Variables[$name] = [Environment]::GetEnvironmentVariable($name, 'User')
}
$backup | ConvertTo-Json -Depth 5 | Set-Content -Encoding UTF8 -Path $backupPath

$currentPath = [Environment]::GetEnvironmentVariable('Path', 'User')
$pathParts = @()
if (-not [string]::IsNullOrWhiteSpace($currentPath)) {
    $pathParts = $currentPath -split ';' | ForEach-Object { $_.Trim() } | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }
}

$managedLookup = @{}
foreach ($entry in $managedPathEntries) {
    $managedLookup[$entry.ToLowerInvariant()] = $true
}

$remainingPathParts = foreach ($part in $pathParts) {
    if (-not $managedLookup.ContainsKey($part.ToLowerInvariant())) {
        $part
    }
}

$newPath = @($managedPathEntries + $remainingPathParts) | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }
[Environment]::SetEnvironmentVariable('Path', ($newPath -join ';'), 'User')

foreach ($name in $managedVariables.Keys) {
    [Environment]::SetEnvironmentVariable($name, $managedVariables[$name], 'User')
}

Write-Host "Locora CurrentUser environment updated."
Write-Host "Backup written to: $backupPath"
Write-Host "Open a new terminal to pick up the updated PATH and LOCORA_* variables."
""";
    }

    private string BuildRemoveScript(
        IReadOnlyCollection<string> pathEntries,
        IEnumerable<string> variableNames)
    {
        return $$"""
# Generated by Locora. Review before running.
# Scope: current Windows user only. No administrator rights are required.
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$managedPathEntries = @(
{{FormatPowerShellStringArray(pathEntries)}}
)

$managedVariables = @(
{{FormatPowerShellStringArray(variableNames)}}
)

$backupRoot = '{{EscapePowerShellSingleQuotedString(_environmentPaths.UserEnvironmentBackupRoot)}}'
New-Item -ItemType Directory -Force -Path $backupRoot | Out-Null
$backupPath = Join-Path $backupRoot ('user-environment-before-locora-uninstall-{0}.json' -f (Get-Date -Format 'yyyyMMdd-HHmmss'))
$backup = [ordered]@{
    CreatedAt = (Get-Date).ToString('o')
    Scope = 'CurrentUser'
    Path = [Environment]::GetEnvironmentVariable('Path', 'User')
    Variables = [ordered]@{}
}
foreach ($name in $managedVariables) {
    $backup.Variables[$name] = [Environment]::GetEnvironmentVariable($name, 'User')
}
$backup | ConvertTo-Json -Depth 5 | Set-Content -Encoding UTF8 -Path $backupPath

$currentPath = [Environment]::GetEnvironmentVariable('Path', 'User')
$pathParts = @()
if (-not [string]::IsNullOrWhiteSpace($currentPath)) {
    $pathParts = $currentPath -split ';' | ForEach-Object { $_.Trim() } | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }
}

$managedLookup = @{}
foreach ($entry in $managedPathEntries) {
    $managedLookup[$entry.ToLowerInvariant()] = $true
}

$remainingPathParts = foreach ($part in $pathParts) {
    if (-not $managedLookup.ContainsKey($part.ToLowerInvariant())) {
        $part
    }
}

[Environment]::SetEnvironmentVariable('Path', ($remainingPathParts -join ';'), 'User')

foreach ($name in $managedVariables) {
    [Environment]::SetEnvironmentVariable($name, $null, 'User')
}

Write-Host "Locora CurrentUser environment entries removed."
Write-Host "Backup written to: $backupPath"
Write-Host "Open a new terminal to pick up the updated PATH."
""";
    }

    private string BuildManifest(
        IReadOnlyCollection<string> pathEntries,
        IReadOnlyDictionary<string, string> variables)
    {
        var now = DateTimeOffset.Now;
        var manifest = new
        {
            Scope = "CurrentUser",
            GeneratedAtLocal = now.ToString("yyyy-MM-dd HH:mm:ss zzz"),
            GeneratedAtUtc = now.UtcDateTime.ToString("yyyy-MM-ddTHH:mm:ssZ"),
            PathEntries = pathEntries,
            Variables = variables,
            InstallScript = _environmentPaths.UserEnvironmentApplyScriptFile,
            UninstallScript = _environmentPaths.UserEnvironmentRemoveScriptFile,
            BackupRoot = _environmentPaths.UserEnvironmentBackupRoot,
            Notes = new[]
            {
                "Locora never changes Machine PATH from these generated scripts.",
                "The persistent PATH entry is limited to usr/aliases.",
                "Built-in Locora terminals prepend active runtime and tool executable folders per session."
            }
        };

        return JsonSerializer.Serialize(manifest, ManifestSerializerOptions);
    }

    private static string FormatPowerShellStringArray(IEnumerable<string> values)
    {
        return string.Join(
            Environment.NewLine,
            values.Select(value => $"    '{EscapePowerShellSingleQuotedString(value)}'"));
    }

    private static string FormatPowerShellHashtable(IReadOnlyDictionary<string, string> values)
    {
        return string.Join(
            Environment.NewLine,
            values.Select(pair => $"    '{EscapePowerShellSingleQuotedString(pair.Key)}' = '{EscapePowerShellSingleQuotedString(pair.Value)}'"));
    }

    private static string EscapePowerShellSingleQuotedString(string value)
    {
        return value.Replace("'", "''", StringComparison.Ordinal);
    }
}
