ServerRoot "D:/Projects/Locora/bin/apache/current"
Listen 8080
ServerName localhost:8080
PidFile "D:/Projects/Locora/temp/apache/httpd.pid"
ErrorLog "D:/Projects/Locora/usr/logs/apache.stderr.log"



<IfModule mime_module>
    # mime.types not found in the Apache package
</IfModule>

DocumentRoot "D:/Projects/Locora/www"
<Directory "D:/Projects/Locora/www">
    Options FollowSymLinks
    AllowOverride None
    Require all granted
    DirectoryIndex index.html index.htm
</Directory>

<FilesMatch "\.php$">
    Require all denied
</FilesMatch>

IncludeOptional "D:/Projects/Locora/usr/config/apache/vhosts/*.conf"